import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

const Satoshi = localFont({
  src: [
    {
      path: "../public/fonts/Satoshi-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-satoshi",
})

const Monument = localFont({
  src: "../public/fonts/MonumentExtended-Regular.woff2",
  weight: "400",
  style: "normal",
  variable: "--font-monument-regular",
})

export const metadata: Metadata = {
  title: "Niftables",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${Satoshi.variable} ${Monument.variable}`}>
      <body>
        <main className="relative">
         <Navbar />
          {children}
          <Footer/>
        </main>
        </body>
    </html>
  );
}
